version: '3.8'

services:
  postgresdb:
    image: postgres:16.0-alpine
    container_name: postgrescontainer
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    networks:
      - securedocnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../SecureDocAIBackend
      dockerfile: Dockerfile
    container_name: backendcontainer
    restart: always
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - securedocnet
    depends_on:
      postgresdb:
        condition: service_healthy

  pgadmin:
    container_name: pgadmincontainer
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 6000
    ports:
      - 7000:6000
    volumes:
      - pgadminvolume:/var/lib/pgadmin

volumes:
  postgresvolume:
  pgadminvolume:

networks:
  securedocnet:
    driver: bridge
